image: registry.gitlab.com/canya-com/node-build-container:1.2

variables:
  APP_PATH: /builds/$CI_PROJECT_PATH

before_script:
  - cd $APP_PATH
  - mkdir -p src/environments
  - touch src/environments/environment.ts
  
stages:
  - build
  - deploy

build:staging:
  stage: build
  only:
    - develop
  artifacts:
    name: "$CI_JOB_NAME"
    paths:
      - $APP_PATH/dist
  script:
    - npm install
    - echo $ENVIRONMENT_STAGING >> $APP_PATH/src/environments/environment.dev.ts
    - npm run build:staging

build:production:
  stage: build
  only:
    - master
  artifacts:
    name: "$CI_JOB_NAME"
    paths:
      - $APP_PATH/dist
  script:
    - npm install
    - echo $ENVIRONMENT_PROD >> $APP_PATH/src/environments/environment.prod.ts
    - npm run build:prod

deploy:staging:
  stage: deploy
  only:
    - develop
  dependencies:
    - build:staging
  script:
    - firebase use canseek-dev
    - firebase deploy --token "$FIREBASE_TOKEN"

deploy:production:
  stage: deploy
  only:
    - master
  dependencies:
    - build:production
  script:
    - firebase use canseek-prod
    - firebase deploy --token "$FIREBASE_TOKEN"
