language: node_js
node_js:
- '8'
before_install:
- openssl aes-256-cbc -K $encrypted_e7d9ab5b8337_key -iv $encrypted_e7d9ab5b8337_iv
  -in aliyun.pem.enc -out ../aliyun.pem -d
install: true
script:
- echo hello>>test.file
- scp -i $encrypted_e7d9ab5b8337_key -o "StrictHostKeyChecking no" test.file root@47.94.194.126:/root
