dist: trusty
addons:
  chrome: stable
language: node_js
node_js:
- "lts/*"
before_install:
- npm install yarn -g
install:
- yarn
script: 
- npm run build
after_script:
- scp -i ${aliyun} -r ./dist root@47.94.194.126:/root/CanSeek/dist
cache:
  directories:
    - node_modules
