language: node_js
node_js:
- "lts/*"
before_install:
- npm install yarn -g
- npm install @angular/cli -g
install:
- yarn && ng add ng-zorro-antd --theme
script:
- git checkout src 
- npm run build
after_script:
- scp -i ${aliyun} -r ./dist root@47.94.194.126:/root/CanSeek
cache:
  directories:
    - node_modules
branches:
  only:
    - dev