language: node_js
node_js:
- '8'
before_install:
- openssl aes-256-cbc -K $encrypted_e7d9ab5b8337_key -iv $encrypted_e7d9ab5b8337_iv
  -in encrypt.zip.enc -out encrypt.zip -d
- unzip -o encrypt.zip
- cp -a encrypt/build .
- cp -a encrypt/firebase/*.* .
- cp -a encrypt/environments src
install:
- npm install yarn @angular/cli firebase-tools -g && yarn
script:
- if [ "$TRAVIS_BRANCH" = "develop" ]; then ENV=dev npm run build && firebase use
  canseek-dev; fi
- if [ "$TRAVIS_BRANCH" = "master" ]; then ENV=prod npm run build && firebase use
  canseek-prod; fi
after_success:
- firebase deploy --token "$FIREBASE_TOKEN"
cache:
  directories:
  - node_modules
branches:
  only:
  - develop
  - master
env:
  global:
    secure: cJqSH7QFMggEaaY5T1m8OQWr8hRfzH7lDOi5WfdWE1JcYtiUYLXthkySR7A3yzJ47nyUFsKhugzHCkCeKKSgx2hZbeB1rHCV10hFIhfjKCH9kmpvRrTzgw+VkZOFYQwKStRrJ4rwah34gajQDuKT+VRcpB6iOdl3hG8hxpJ0OHniY48a2s81fewP0QMeXL0RwFmzJfeg3OfSNeem/xXAUVcpxMvXuDyulnjyPtJJLVbt/OG2PNiqJYJots2O+u+0z9i6e/VdSrD6idFDBWv8tK0NagRXDe1Jq2v8al/Jv8RSWT4C3UVMCidC14tNLrKnvml1gNHP6fKEwJ7XU8aXDlz4peW9efZjQRDrrElAKwxyYCvW7+6Wjpezb1zjyjS9ejWXpq0Cd3fmjsu00eHKEKAB1kgacA2lOCqSq9MqLMtLD7lF3JRMEYvu5k1oQOjp5suAixcNjIEP2FnfvH8lLXR3CYnUa34kzGHdTDZeuhxQW06aIGJ3+dhIquqef/65X5Dl0ALJAdUF99y0U80M1PRS7hXIMtjcvarecoAJ4KqVpbhAIJJo/EroI3RuqzHJEEehn74GG6/QjsXDjw1ZGWIJ/38zy4QUmbgxsee19LsU+kszm8gCQx2v3O8QzMWN2Ir06I+5xkvhzhhv0bpRJpNBAKYakF8w7tRkS+lo8i4=
notifications:
  slack:
    secure: FF/gECqVBVfYXxFwwqPPyZBrInVC5fvYjFPgTlDhSjjVUgTCRS2ZyQ0Kb8jp1Jx1PQI7/0PJxtghQeeblDa9DPHNuQ0Ags9Z3zLMjA1bAPw4cDz3/v/0Kb03fK+nyTy2R0qRt3pGiX/F20ob8OlXLFaWs0EX163BB/RGDALqCbdFotkZ71ufvWu0v+jtuQrqE1P5JAQBEy6/jAmicbUkS5QMVluNu23zi5bU60IYXCuX592Sy+HAPC/VDUjbJ+WqkHv35jetDpiIJz1DYi/KXRiavpR/Y4XbRdcsXppQ/3HEZ2Mo+GaI0QE/UKUnAMIZmCeuM5x0CJ6PKIygiutaIGG9L7+gLr7z8/GOnb456B0IsxQiLzDk7jLLknwrc15d5HnBnnYZ0MEirdsByLs6BfDAkVFhjZKZz1c7fgRiAF4Mp44tqX6IJJqpnRyTr9/6p0LqUfbKasSkaDsKOPzI860NMifUs83dfjKKcYuMR20gu0/nhEhe5fcchngRBCbZNxcLkP8uYo9Qfb4ByaVN7F+BDPQVAshsZyIqyhhBBuHcceK0NkYY+GnBiIrFj8HCK8PypL3AWVuHVeT2QfJukrE8xlgWwXZ4C2Es8aVV+1Anb0wq4sy0puUo4F4iMlFFuTn2UZBvAAOzelH9fQ/zuO0SVmOrB9+q4Uphohzd9lI=
