language: node_js
node_js:
- '8'
before_install:
- openssl aes-256-cbc -K $encrypted_e7d9ab5b8337_key -iv $encrypted_e7d9ab5b8337_iv
  -in encrypt.zip.enc -out encrypt.zip -d
- unzip -o encrypt.zip
- mv encrypt/build .
- mv encrypt/firebase/* .
- mv encrypt/environments src/
- mv encrypt/aliyun.pem .
install:
- npm install yarn @angular/cli firebase-tools -g && yarn
script:
- ENV=dev npm run build && firebase deploy --token "$FIREBASE_TOKEN"
cache:
  directories:
  - node_modules
branches:
  only:
  - test_ci
notifications:
  slack:
    secure: N285/hD0iEAxgXBX9qv8a3DaPG6nyj12GrPaUVVjEHW9spXywOdsx6XGnC5CMClgc9+7m/YgE+uWzLlwYavMe95UvfoxRqYTPq+OJ8PP1NRxaDPzogNs5C/PXsaFx/Kb9MAbkO/20UM5KIQVkF9y5ocF7S4gWJPUXkjx7sM6qmP8c8fQVCr2hFKx95MK9/MXAXHuOOULEqqEUNLp5ltjbmt5ek+XjxkCpfHSxJI1VSzXRl+uQzW9nXMuN+IKmd/+nfsuhIXZFqZcapF6DCySO469fO4V5powALmzZPtl66xXR+lYLpRCCMRsi1YQ0qxtu6H1M5Ul4S5OqTG5r/ItS34mi2qnxCFNLbsGS+GU7wsVDZm4nKmvAFEYD/sEM6Op5u5eRv9Kc9SjNhBDQJocq9fiX5gGcIYpy0umkpO67JV8GSqc8RylQR/rKZmAtiT+qVYl41mBuaG3yLPb5UV9J9hxO1b+QaXW9iUmZFfXQYPhF1pO82l1FL2zQaoBgdpzXaJj0o5AqfEBp8sponpd+N0vpsY0Ai4x4FkIpr7hTzLADRjzuQzn73+iKv/ruhuG4PKW0+qW8wiKQmkO+i8WLKMBeBAnCfvBZfQZ4fGor7pjg+zMQrZyIjHru1Q1MvUN2i6oRuwdXcM4gbBxvJLsfvn0Lcd7PDMwae9AmBx1c+w=
env:
  global:
    secure: cJqSH7QFMggEaaY5T1m8OQWr8hRfzH7lDOi5WfdWE1JcYtiUYLXthkySR7A3yzJ47nyUFsKhugzHCkCeKKSgx2hZbeB1rHCV10hFIhfjKCH9kmpvRrTzgw+VkZOFYQwKStRrJ4rwah34gajQDuKT+VRcpB6iOdl3hG8hxpJ0OHniY48a2s81fewP0QMeXL0RwFmzJfeg3OfSNeem/xXAUVcpxMvXuDyulnjyPtJJLVbt/OG2PNiqJYJots2O+u+0z9i6e/VdSrD6idFDBWv8tK0NagRXDe1Jq2v8al/Jv8RSWT4C3UVMCidC14tNLrKnvml1gNHP6fKEwJ7XU8aXDlz4peW9efZjQRDrrElAKwxyYCvW7+6Wjpezb1zjyjS9ejWXpq0Cd3fmjsu00eHKEKAB1kgacA2lOCqSq9MqLMtLD7lF3JRMEYvu5k1oQOjp5suAixcNjIEP2FnfvH8lLXR3CYnUa34kzGHdTDZeuhxQW06aIGJ3+dhIquqef/65X5Dl0ALJAdUF99y0U80M1PRS7hXIMtjcvarecoAJ4KqVpbhAIJJo/EroI3RuqzHJEEehn74GG6/QjsXDjw1ZGWIJ/38zy4QUmbgxsee19LsU+kszm8gCQx2v3O8QzMWN2Ir06I+5xkvhzhhv0bpRJpNBAKYakF8w7tRkS+lo8i4=
